{
 "title": "Mirrors Banner",
 "description": "具象化显示 Mirrors Banner 暴露的指标",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Banned IPv4 最后一次访问时间",
   "type": "table",
   "description": "显示被 Ban 的 IPv4 IP 的最后一次访问时间",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ipv4_banned_last_access_time{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Banned IPv6 最后一次访问时间",
   "type": "table",
   "description": "显示被 Ban 的 IPv6 IP 的最后一次访问时间",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ipv6_banned_last_access_time{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Banned IPV4 继续访问次数",
   "type": "timeseries",
   "description": "显示被 Ban 的 IPv4 IP 的访问次数",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
   "targets": [
    { "expr": "ipv4_banned_access_times{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Banned IPV6 继续访问次数",
   "type": "timeseries",
   "description": "显示被 Ban 的 IPv6 IP 的访问次数",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 25 },
   "targets": [
    { "expr": "ipv6_banned_access_times{}", "legendFormat": "__auto" }
   ]
  }
 ]
}